
#????????url?username?password?????????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu?serverTimezone=Asia/Shanghai&characterEncoding=utf8&serverTimeZone=Asia/Shanghai
    username: root
    password: root
#??????,??????????????????????(resultType)
#subject_id ? subjectId
mybatis:
  configuration:
  # map-underscore-to-camel-case: true  # ??????
  mapper-locations: classpath:mappers/*.xml
#  type-aliases-package: cn.tedu.pojo

#????
logging:
  level:
    cn.tedu.mybatisdemo: debug

